name: Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  teste:

    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Verificar projeto
        run: echo "Pipeline funcionando!"